### ISSUE TITLE
Breakfast Club

### ISSUE THREAD

**Issue by rhmnm** [foundersandcoders/gaza-delights#2]
@mantagen @saralk Guys, we need to have a Breakfast Club charter. Kind of like the rules of Fight Club, but for Breakfast Club so that as new FAC people join the GSG fam, they're properly onboarded to the culture and art of Breakfast Club. Let's discuss this during our first e-pilates session.

**Comment by mantagen** [comment]
Agreed. We can't let this get slack!

**Comment by rhmnm** [comment]
Some initial rules off the top of my head:

- Stay hydrated
- Pass the coffee 
- Be kind 
- Friendship is the cornerstone of breakfast club
- If there's not enough figs for everyone, please don't serve figs with breakfast and let them be snacks during prep and clean-up
- Omelettes should be fluffier than frittatas. Frittatas should be judged on structural integrity first and foremost.
- Boiled eggs > no eggs

**Comment by rhmnm** [comment]
@mantagen @m4v15 @ZooeyMiller @saralk @eliascodes WE'RE SLACKING ON THIS ISSUE

**Comment by eliasmalik** [comment]
Is this the live repo, or is it [this one](https://github.com/gazaskygeeks/gaza-delights)? We should use either one or the other, otherwise I will be confused 😕

**Comment by rhmnm** [comment]
@eliascodes It should be the other one, but we have **so** many issues in this one. We're trying to figure out the best way out of this disaster.
